#!/usr/bin/env bash
# Script to install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx restart
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

searchString="^\tlocation / {"
replaceString="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo sed -i "s@${searchString}@${replaceString}@" /etc/nginx/sites-available/default

sudo service nginx restart
