#!/usr/bin/env bash
# Script to install nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx restart
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/custom_404.htm
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
searchStr="^\tlocation / {"
replacestr="\terror_page 404 /custom_404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${searchStr}@${replacestr}@" /etc/nginx/sites-available/default

sudo service nginx restart
