#!/usr/bin/env bash
# Script to install haprox (load balancer)

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy=1.6.\*

str="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver web01 54.146.224.251:80 check\n\tserver web02 3.90.2.212:80 check"

sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
