#!/usr/bin/env bash
# Script uses the -- while-loop -- to print 10x the string "Holberton School"
# on the 9th iteration, print "hi"
i=0
while [ $i -lt 10 ];
do
	echo "Holberton School"
	let i+=1
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
done	
