#!/usr/bin/env bash
# Script uses the -- while-loop -- to print 10x the string "Holberton School"
# on the 4th and 8th iter. change print
i=1
while [ $i -le 10 ];
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
	echo "Holberton School"
	fi
	((++i))
done	
