#!/usr/bin/env bash
# Script uses the -- while-loop -- to print numbers 1-20
# After the 4th, 9th, and 17th iter. print speciefied string
i=1
while [ $i -le 20 ];
do
	echo $i
	case $i in
	4)
		echo 'bad luck from China'
		;;
	9)
		echo 'bad luck from Japan'
		;;
	17)
		echo 'bad luck from Italy'
		;;
	esac
	((++i))
done
