#!/usr/bin/env bash
# script uses while loop to print time: hours fro 0-12, and min from 1-59
hr=0
while [ $hr -le 12 ]
do
	echo Hour: $hr
	min=1
	while [ $min -le 59 ]
	do
		echo $min
		((++min))
	done
	((++hr))
done
