#!/usr/bin/env bash
# Install a load balancer using HAProxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy
sudo service haproxy start

str="\nglobal\n\tuser haproxy\n\tgroup haproxy\n\tdaemon\n\nfrontend http_in\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 2314-web-01 34.224.166.248:80 check\n\tserver 2314-web02 34.229.12.49:80 check"

sudo echo -e "$str" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
